### PR TITLE
fix: use correct default branch name for Snyk workflow

### PR DESCRIPTION
**Pull request by jfsoul**
Updates this repository's Snyk integration to use the correct branch name in the workflow trigger.

### CODE REVIEW

**Comment by ParisaTork** [comment]
Hi @jfsoul, we're going to master-to-main this repo on Monday - this repo had issues the last time it was master-to-mained and so it was switched back to master (see issue #28) - this revert took place after the Snyk integration (which specifies main as the target branch) - therefore, we're taking extra precautions with this one.

**Comment by jfsoul** [comment]
Thanks @ParisaTork, is this PR correct in keeping the Snyk org as CAPI's, or is #30 correct in updating it to be Ed tools'? I'll close one of them!

**Comment by ParisaTork** [comment]
Hi @jfsoul :) I think content-entity is used by Ed Tools, CAPI and Dotcom, but if you fancy putting the org down as Ed Tools since we're sorting it, you're more than welcome to - equally, it would be fine if things stay the same and CAPI is listed as the Snyk org

**Comment by ParisaTork** [comment]
This repo has been a finicky repo to m2m, so Snyk will point to master with this PR merge and the m2m-ing of this repo will occur later.

**Pull request merged**
